### ISSUE TITLE
Migrate to portable

### ISSUE THREAD

**Issue by alexshikov** [digitalcreations/CustomerIOSharp#1]
Please consider migration to PCL.
Here is a rough migration example https://github.com/SeeD-Seifer/CustomerIOSharp/commit/7e1b45965a7a9cafe601607323631375b43c91f0 though maybe you will have better solution.

**Comment by vegardlarsen** [comment]
@SeeD-Seifer I'd appreciate a pull request for this, and I'd merge it if it works equally well. :)

**Comment by vegardlarsen** [comment]
See #2.
