### ISSUE TITLE
Appears Successful, CustomerIO not receiving events

### ISSUE THREAD

**Issue by fahall** [digitalcreations/CustomerIOSharp#9]
Hello,

I'm trying to get CustomerIOSharp working within Unity 2018.1.9f2. I'm using Unity's .NET 4.x support, so everything should be working just fine. My code appears to be calling into the API correctly, but for some reason CustomerIO is not receiving either the events or the user property update. I am not catching any exceptions (though I'm fairly new to async in C# and may be making a mistake). Is there's something I'm missing here? 

I've done some simple curl calls with my siteId and apiKey for sanity, and those work fine.

My wrapper looks like this:

```C#
public CustomerIOWrapper()
{
    _customerIo = new CustomerIo(_siteId, _apiKey);
}

public Task UpdateUser(IAnalyticsEventReport report)
{
    try
    {
        return _customerIo.IdentifyAsync(report.Dossier.ToCustomer());
    }
    catch (CustomerIoApiException e)
    {
        Dbg.WarningFormat("#customerio HTTP Response: {0}, Reason: {1}", e.HResult, e.Message);
        return new Task(() => Dbg.WarningFormat("#customerio HTTP Response: {0}, Reason: {1}", e.HResult, e.Message));
    }
}

private Task TrackEventAsync(string customerId, string eventName, IDictionary<string, object> data)
{
    Dbg.LogFormat("#customerio #analytics CustomerIO customerId: {0}", customerId);
    try
    {
        return _customerIo.TrackEventAsync(eventName, data, customerId: customerId);
    }
    catch (CustomerIoApiException e)
    {
        Dbg.WarningFormat("#customerio HTTP Response: {0}, Reason: {1}", e.HResult, e.Message);
        return new Task(() => Dbg.WarningFormat("#customerio HTTP Response: {0}, Reason: {1}", e.HResult, e.Message));
    }
}
```

Am I missing something stupid here? 

Is there a better way I can log out the results from the HTTP call?

**Comment by vegardlarsen** [comment]
You are missing `async/await` on your methods. When you don't await the `IdentifyAsync` call, the exception cannot be caught (because it happens after the method has returned).

Take these two simplified examples, if you await both of them, you will see the difference. In `CatchWithAsync`, the exception is caught as expected. In `CatchWithoutAsync`, the exception is thrown and escapes to the global exception handler.

```cs
public async Task CatchWithAsync()
{
	try
	{
		await SomethingAsync();
	}
	catch (NotImplementedException)
	{
		Debug.WriteLine("This will trigger");
	}
}

public Task CatchWithoutAsync()
{
	try {
		return SomethingAsync();
	}
	catch (NotImplementedException) {
		Debug.WriteLine("This never triggers");
		return Task.FromResult(42);
	}
}

public Task SomethingAsync() {
	return Task.Factory.StartNew(() => throw new NotImplementedException());
}
```
